language: rust
matrix:
  include:
  - os: linux
    rust: 1.15.1
  - os: linux
    rust: stable
  - os: linux
    rust: beta
  - os: linux
    rust: nightly
  - os: osx
    osx_image: xcode7.3
    rust: stable
  - os: osx
    osx_image: xcode8
    rust: stable
script:
- |
  env RUST_BACKTRACE=1 cargo test --verbose --all
